name: deb-on-24.04wCpack

on: 
  workflow_dispatch:      # allows manual trigger
  schedule:
    - cron: "0 6 * * *"   # runs daily at 06:00 UTC

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # This yml is copied from https://github.com/hn-88/OCVWarp/blob/master/.github/workflows/cmake-nix.yml
  # and modified.
  BUILD_TYPE: Release
  # As recommended here: https://github.com/marketplace/actions/sccache-action
  OPENSPACE_VERSION: "0.21.3plus"
  APPIMAGE_VERSION: "1"
  # COMMIT_HASH: "0bec798cb39c2765373283a21312478d3d2e3c7f"
  COMMIT_HASH: "master"
  
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: true
        swap-storage: false
    
    - name: get openspace code for a particular release
      # https://docs.openspaceproject.com/releases-v0.20/contribute/development/compiling/ubuntu.html
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        git clone --recursive https://github.com/OpenSpace/OpenSpace "$openSpaceHome"
        cd "$openSpaceHome"
        git checkout "${COMMIT_HASH}" --recurse-submodules
        # try the latest main branch, one of the latest commits
        mkdir build
        cd build

    #- name: get updated ghoul
      # https://github.com/OpenSpace/OpenSpace/issues/3880
      #run: |
        #openSpaceHome="$HOME/source/OpenSpace"
        #cd "$openSpaceHome/ext/ghoul"
        #git checkout master --recurse-submodules
    
    - name: Install dependencies
      # https://docs.openspaceproject.com/releases-v0.20/contribute/development/compiling/ubuntu.html
      run: |
        sudo apt update
        sudo apt-get -y install glew-utils libpng-dev freeglut3-dev git libxrandr-dev libxinerama-dev xorg-dev libxcursor-dev libcurl4-openssl-dev libxi-dev libasound2-dev libgdal-dev libboost-all-dev qt6-base-dev libmpv-dev libvulkan-dev
        sudo apt-get -y install software-properties-common
        sudo apt-get -y install libasound2t64 
        # libasound2-data libasound2-plugins

    #- name: Install clipboard patches
    #  run: |
    #    openSpaceHome="$HOME/source/OpenSpace"
        # cp -vf Ghoul-src-misc-clipboard.cpp "$openSpaceHome/ext/ghoul/src/misc/clipboard.cpp" 
        
    - name: Install cmakelists patches
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        cp -vf deb-patches/*.diff "$openSpaceHome"
        cd $openSpaceHome
        git apply --verbose fix-Windows-Cpack-zip.diff
        
    - name: Install deb patches
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        cd $openSpaceHome
        git apply --verbose DebwithCPack.diff

    - name: Install png for deb
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        cp -vf deb-patches/openspace.png "$openSpaceHome/support/deb/openspace.png"


  
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        cd "$openSpaceHome/build"
        echo "Please note the extra variables passed for making the deb package ..."
        cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_COMPILER=/usr/bin/g++-13 -DCMAKE_C_COMPILER=/usr/bin/gcc-13 \
          -DCMAKE_CXX_STANDARD=20 -DASSIMP_BUILD_MINIZIP=1 -DBUILD_TESTS=OFF -DOPENSPACE_HAVE_TESTS=OFF -DSGCT_BUILD_TESTS=OFF \
          -DOPENSPACE_DISTRO=ubuntu24.04 -DCMAKE_INSTALL_PREFIX=/usr "$openSpaceHome"

    - name: Build
      # Build your program with the given configuration
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        cd "$openSpaceHome/build"
        # Use the system's libvulkan, not the vendored one, otherwise they might conflict
        cef_orig_dir=$(find $HOME/source/OpenSpace/build -path */Release/libcef.so | xargs dirname)
        rm -v $cef_orig_dir/libvulkan.so.1
        cmake --build . --parallel 3
        
    - name: Create deb
      working-directory: ${{github.workspace}}
      # https://github.com/hn-88/OpenSpace-AppImage/blob/main/.github/workflows/build-on-ghcr-24.04.yml was running out of disk space
      run: |
        openSpaceHome="$HOME/source/OpenSpace"
        cd "$openSpaceHome/build"
        echo "Check for disk space..."
        df -h
        echo "Running CPack to create deb installer..."
        DATE=$(date +%Y%m%dT%H%M%S)
        cpack -G DEB 
        # mv -v openspace*.deb openspace_0.21.2-2~ubuntu24.04.1_amd64_${DATE}.deb 
        mv -v openspace*.deb openspace_0.21.3+~ubuntu24.04_amd64_daily.deb
         # Test the rpaths when deb is built with
        # readelf -d deb_extract/usr/share/openspace/bin/OpenSpace | grep RPATH
        # ldd deb_extract/usr/share/openspace/bin/OpenSpace
        
    - name: Upload AppImage Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: OpenSpace-Deb-Cpack
        # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/source/OpenSpace/build/openspace*.deb

    - name: Upload .deb to GitHub Release
      run: |
        RELEASE_TAG="daily-CPACK-DEB"
        DEB_FILE="/home/runner/source/OpenSpace/build/openspace*.deb"
    
        # Create release if it doesn't exist
        gh release view "$RELEASE_TAG" >/dev/null 2>&1 || \
          gh release create "$RELEASE_TAG" -t "OpenSpace CPack Daily Build" -n "Automated daily .deb build of OpenSpace."
    
        # (Optional) update title/notes each run
        gh release edit "$RELEASE_TAG" \
          -t "OpenSpace CPack Daily Build" \
          -n "Automated daily build of OpenSpace (updated $(date '+%Y-%m-%d %H:%M:%S') UTC).  On installing this .deb file, you can run openspace by typing 'openspace' in a terminal window. '/usr/bin/openspace' contains a script which sets the user directory and other env variables, which you can change as desired. Please note all the issues at https://github.com/hn-88/OpenSpace-AppImage/issues?q=is%3Aissue%20state%3Aopen%20deb%20created%20with%20cpack"
    
        # Upload .deb asset (overwrite if exists)
        gh release upload "$RELEASE_TAG" "$DEB_FILE" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}


      
    
